"""db migration

Revision ID: ce1475732dc0
Revises: 
Create Date: 2024-09-16 11:19:45.024000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce1475732dc0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_User_email', table_name='User')
    op.drop_index('ix_User_id', table_name='User')
    op.drop_index('ix_User_username', table_name='User')
    op.drop_table('User')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(), nullable=True),
    sa.Column('verification_code', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_User_username', 'User', ['username'], unique=1)
    op.create_index('ix_User_id', 'User', ['id'], unique=False)
    op.create_index('ix_User_email', 'User', ['email'], unique=1)
    # ### end Alembic commands ###
